# **Importing the libraries**

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [4]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix,accuracy_score

# **Splitting The Data**

# **SPLIT THE DATA INTO INDEPENDENT VARIABLES**

In [13]:
X = DS.iloc[:, :-1].values
print(X)

[[    1    -1     1 ...     1     1    -1]
 [    2     1     1 ...     1     1     1]
 [    3     1     0 ...     1     0    -1]
 ...
 [11053     1    -1 ...     1     0     1]
 [11054    -1    -1 ...     1     1     1]
 [11055    -1    -1 ...    -1     1    -1]]


# **SPLIT THE DATA INTO DEPENDENT VARIABLES**

In [15]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
DS[["port"]] = scaler.fit_transform(DS[["port"]])
  
print(DS)

       index  having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0          1                          -1              1                   1   
1          2                           1              1                   1   
2          3                           1              0                   1   
3          4                           1              0                   1   
4          5                           1              0                  -1   
...      ...                         ...            ...                 ...   
11050  11051                           1             -1                   1   
11051  11052                          -1              1                   1   
11052  11053                           1             -1                   1   
11053  11054                          -1             -1                   1   
11054  11055                          -1             -1                   1   

       having_At_Symbol  double_slash_redirecting  